### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by MounikaKolisetty** [ddobric/neocortexapi#17]
Hello Professor

I was trying to create an instance of column class. The property ConnectedInputBits is initiated as "Column.ConnectedInputBits throws an exception of the type system.NullReferenceException"

![image](https://user-images.githubusercontent.com/56874374/125158621-893e1280-e172-11eb-88ac-e69f10c1be58.png)

Can you please suggest to me a solution to overcome the issue?

Regards
Mounika

**Comment by QuangBui3101** [comment]
Hi Mounika,

how did you create the Column object, was it created by the parameterless constructor?
You should use this instead:
```cs
        /// <summary>
        /// Creates a new collumn with specified number of cells and a single proximal dendtrite segment.
        /// </summary>
        /// <param name="numCells">Number of cells in the column.</param>
        /// <param name="colIndx">Column index.</param>
        /// <param name="synapsePermConnected">Permanence threshold value to declare synapse as connected.</param>
        /// <param name="numInputs">Number of input neorn cells.</param>
        public Column(int numCells, int colIndx, double synapsePermConnected, int numInputs)
        {
            this.Index = colIndx;

            this.hashcode = GetHashCode();

            Cells = new Cell[numCells];

            for (int i = 0; i < numCells; i++)
            {
                Cells[i] = new Cell(this.Index, i, this.GetNumCellsPerColumn(), this.CellId, CellActivity.ActiveCell);
            }

            // We keep tracking of this column only
            this.connectedInputCounter = new SparseBinaryMatrix(new int[] { 1, numInputs });

            ProximalDendrite = new ProximalDendrite(colIndx, synapsePermConnected, numInputs);

            this.ConnectedInputCounterMatrix = new SparseBinaryMatrix(new int[] { 1, numInputs });
        }
```

For reference, please take a look at the following unit test
[GeneralUnitTests.cs](https://github.com/ddobric/neocortexapi/blob/bc7764bafb83f99e79b9e64f743a057eb2334847/source/UnitTestsProject/GeneralUnitTests.cs) method ColumnCompareTest

Regards,
Quang

**Comment by MounikaKolisetty** [comment]
Hi Quang 
Thanks for your response. Yes, I am using a parameterless constructor since I need to deserialise the text file into an empty Column object.

![image](https://user-images.githubusercontent.com/56874374/125163817-3e7ec380-e18f-11eb-82b0-0f1bca8e74c7.png)

and the property ConnectedInputBits is not able to initialise as it has only get attribute.

Regards
Mounika
