### ISSUE TITLE
Discussion on Project Video Learning using HTM CLA

### ISSUE THREAD

**Issue by Noath2302** [ddobric/neocortexapi#18]
please refer to the document at https://github.com/ddobric/neocortexapi/tree/SequenceLearning_ToanTruong/ProjectDOC

**Comment by ddobric** [comment]
1. You should better describe your approach. What does it mean Video Learning?
2. You should describe METHODS, means how do you do video learning. I.e.: extract frames (in lines ??) then learn frames, then ??
3. Obstacles. Not sure, but I think you are using the old version of the classifier. The new one predicts multiple inputs. Moreover, the the named Assertion is not appropriate for your case. We need to figure out some other one.
4. Why is current encoding an obstacle?
5. 

> How to predict backward an image from an SDR ?
The classifier is doing exactly that cls.GetPredictedValues()

6. 
> How to learn each videos respectively with a label ?
We need to figure out that. This kind of labeling is still kind of open task.

**Comment by Noath2302** [comment]
thank you for your answer,
2. My current work on the project  
- I [extract all frame from all videos and store them in an object type VideoSet](https://github.com/ddobric/neocortexapi/blob/0dd82bc17f1302e463da719f7e7351a4eabc2baf/Project12_HTMCLAVideoLearning/HTMVideoLearning/VideoSet/VideoSet.cs#L67-L79)
- I [feed all frames respectively to the SP learning](https://github.com/ddobric/neocortexapi/blob/0dd82bc17f1302e463da719f7e7351a4eabc2baf/Project12_HTMCLAVideoLearning/HTMVideoLearning/VideoLearningUnitTest/VideosExperiment.cs#L199-L216)
- Do predict (I am not sure at the moment how this work)
4. During the reading of frame I convert the pixel color channel to binary bit array, see ([enum ColorMode](https://github.com/ddobric/neocortexapi/blob/0dd82bc17f1302e463da719f7e7351a4eabc2baf/Project12_HTMCLAVideoLearning/HTMVideoLearning/VideoSet/VideoSet.cs#L18-L36), [BitmapToBinaryArray](https://github.com/ddobric/neocortexapi/blob/0dd82bc17f1302e463da719f7e7351a4eabc2baf/Project12_HTMCLAVideoLearning/HTMVideoLearning/VideoSet/VideoSet.cs#L154-L186) ).  
These binary array however is not semantically continous for near color value e.g. 01111111 next value is 10000000. I am planning to used **graycode** for the encoding.  

another problem which I afraid is it makes the InputBitArray space very large:  
- Number<sub>pixel</sub>/frame x 8bit/channel x 3 channel/pixel = Number<sub>bit</sub>/frame
- Number<sub>Available InputBitArray</sub> = 2<sup>Number<sub>bit</sub>/frame</sup> = 2<sup>2400</sup> for a 10x10 resolution frame.

1 and 6. I am not sure either, but I have 2 thougths:
**First approach** SP + TP Learning learns and predict the next possible frames
- this approach requires the input videos to have a small set of available outcome and an "overall rule" of the video with little variation, like the bouncing ball. 
- With the "rule" that the ball always moves in constant speed/ frame and bounces when it reach the border, we can satisfy both requirements: smaller set of videos and having a rule. 
- This rule also helps to visually evaluate the learning process.

**Second Approach** Learning stream of label in the Video 
- We label each frames on the learning VideoSet for the project, this can be done by extracting the binary array from the [BitmapToBinaryArray](https://github.com/ddobric/neocortexapi/blob/0dd82bc17f1302e463da719f7e7351a4eabc2baf/Project12_HTMCLAVideoLearning/HTMVideoLearning/VideoSet/VideoSet.cs#L154-L186) method to a csv files.  
- Then we manually add label to each frame  
- e.g. if a frame has a cat, tree, bush, a house, a pavement, we add the set {cat, tree, bush, house, pavement} as label of the encoded frame.
- The video will proceed with the addition or subtraction of some labels in the coming frames.
- After feeding the encoded frame to the GetPredictedValues, I hope to get the label set associates with the frame and the prediction of coming labels.

**Comment by ddobric** [comment]
You should use ImageBinarizer for "graycode"
