### ISSUE TITLE
Missing Learning Foundation API -Htm Sequence Learning

### ISSUE THREAD

**Issue by rprajwaln** [ddobric/neocortexapi#4]
Yes Professor I am working in neocortex
![image](https://user-images.githubusercontent.com/56980973/105996088-2d8f3980-60aa-11eb-8017-00430447c51c.png)
![image](https://user-images.githubusercontent.com/56980973/105996250-5e6f6e80-60aa-11eb-8302-2795cb304acb.png)
![image](https://user-images.githubusercontent.com/56980973/105996298-6c24f400-60aa-11eb-8f0d-b3fbadbd3c4c.png)

**Comment by QuangBui3101** [comment]
Hi @rprajwaln ,

could you try to clear the local storage of nuget packages on your machine. It could be that the solution is restored from old ImageBinarizer nuget package. Here is the path to the local storage: 

> C:\Users\\*Replace with your username on your machine*\\.nuget\packages

By the way, what happened with these nuget packages? Are they missing or just that your IDE cannot recognize them?
![image](https://user-images.githubusercontent.com/33340665/106003642-b01bf700-60b2-11eb-8570-bc2397b5b9b0.png)

Quang

**Comment by rprajwaln** [comment]
Hello @QuangBui3101 

Thank you for your reply. I am using Rider IDE , I have added all the necessary nuget packages and I have specified the local path correct nuget . Is it possible to resolve this over a call.

**Comment by QuangBui3101** [comment]
Hi @rprajwaln ,

we can arrange a call tomorrow. Could you send me your email address over to my address nqbui@daenet.com. I will try to invite you to a Teams call.
