### ISSUE TITLE
Trace SDR Merge for NeoCortexApi

### ISSUE THREAD

**Issue by Noath2302** [ddobric/neocortexapi#71]
I have added the Trace SDR method **"StringifyTraceSDR"** to [Helpers.cs](https://github.com/ddobric/neocortexapi/blob/9cdad4c71542bd62205fa3bf06e43d15ff63217e/source/NeoCortexApi/Helpers.cs#L35-L147)

The Tests are currently located at [**"TraceSDRsTest.cs"**](https://github.com/ddobric/neocortexapi/blob/SDRTraceMerge/source/UnitTestsProject/TraceSDRsTest.cs) 

I don't know yet where can I put the md file and pdf file of the project.

**Comment by sabinbajracharya** [comment]
Documentation available at [ML-21-22-26_Implement_Trace_SDR_Method.pdf](https://github.com/ddobric/neocortexapi/blob/SDRTraceMerge/source/Documentation/ML-21-22-26_Implement_Trace_SDR_Method.pdf)
